- host: all
  - name: Install Maeven
    ansible.builtin.apt:
      name: maven, docker
      state: present

  - name: Set Up Database
    community.docker.docker_container:
      image: mariadb:latest
      env: 
        MARIADB_ROOT_PASSWORD: "root_pwd"

  - name: Clone Porject
    ansible.builtin.git:
      repo: https://gitlab.com/bbwrl/m346-ref-card-03.git
      dest: /ref03

  - name: Build Ref03
    ansible.builtin.command:
      cmd: mvn clean install
      chdir: /ref03
 
  - name: Start Ref03
    ansible.builtin.command:
      cmd: java -DB_USERNAME="root" -DB_PASSWORD="root_pwd" -jar  target/architecture-refcard-03-0.0.1-SNAPSHOT.jar &
      chdir: /ref03