- name: Install Docker and Python
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - docker.io
    - docker-compose
    - python3
    - python3-pip

- name: Clone Ref03 repository
  ansible.builtin.git:
    repo: https://gitlab.com/bbwrl/m346-ref-card-03.git
    dest: /ref03

- name: Install Docker Python library
  ansible.builtin.pip:
    name: docker
    state: present

- name: docker compose
  ansible.builtin.docker_compose:
    project_src: /ref03
